<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yorum_like_button_icon</name>
   <tag></tag>
   <elementGuidId>c5a7f522-0225-47dd-abe7-fbf276545648</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.like_btn.share._share.empty > div.like_button_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='post654155741_23']/div/div[2]/div/div[2]/div/div/a[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>like_button_icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post654155741_23&quot;)/div[@class=&quot;_post_content&quot;]/div[@class=&quot;post_content&quot;]/div[@class=&quot;post_info&quot;]/div[@class=&quot;like_wrap _like_wall654155741_23&quot;]/div[@class=&quot;like_cont&quot;]/div[@class=&quot;like_btns&quot;]/a[@class=&quot;like_btn share _share empty&quot;]/div[@class=&quot;like_button_icon&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post654155741_23']/div/div[2]/div/div[2]/div/div/a[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
