<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Topluluk olutur_ui_search_button_search _ui_search_button_search</name>
   <tag></tag>
   <elementGuidId>1331f7f5-aa39-441c-af16-51434a39433d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui_search_button_search._ui_search_button_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='group_u_search_input_wrap']/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui_search_button_search _ui_search_button_search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Topluluk ara</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group_u_search_input_wrap&quot;)/div[@class=&quot;ui_search_new ui_search groups_list_search _wrap&quot;]/div[@class=&quot;ui_search_input_block&quot;]/button[@class=&quot;ui_search_button_search _ui_search_button_search&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group_u_search_input_wrap']/div/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
   </webElementXpaths>
</WebElementEntity>
